### ISSUE TITLE
Import error on startup 

### ISSUE THREAD

**Issue by philipmjohnson** [morea-framework/morea-lintui#2]
I'm getting this error:

```
[~/github/philipmjohnson/ics314f15]-> ./morea-lintui.py 
Traceback (most recent call last):
  File "./morea-lintui.py", line 8, in <module>
    from MOREA.MoreaContent import MoreaContent
ImportError: No module named MOREA.MoreaContent
```

**Comment by philipmjohnson** [comment]
Here is a log of my installation steps:

```
[~/github/philipmjohnson/ics314f15]-> python --version
Python 2.7.10
[~/github/philipmjohnson/ics314f15]-> cd 
[~]-> cd Desktop/
[~/Desktop]-> chmod 775 get-pip.py 
[~/Desktop]-> sudo python get-pip.py 
Password:
The directory '/Users/philipjohnson/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/philipjohnson/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 400kB/s 
Collecting wheel
  Downloading wheel-0.26.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 65kB 4.5MB/s 
Installing collected packages: pip, wheel
Successfully installed pip-7.1.2 wheel-0.26.0
[~/Desktop]-> sudo -H python get-pip.py 
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages
[~/Desktop]-> pi
pic          pico         piconv5.16   pictd        ping         pip          pip2.7       
pic2graph    piconv       piconv5.18   pidpersec.d  ping6        pip2         
[~/Desktop]-> pi
pic          pico         piconv5.16   pictd        ping         pip          pip2.7       
pic2graph    piconv       piconv5.18   pidpersec.d  ping6        pip2         
[~/Desktop]-> pip install urwid
Collecting urwid
  Downloading urwid-1.3.0.tar.gz (580kB)
    100% |████████████████████████████████| 581kB 830kB/s 
Building wheels for collected packages: urwid
  Running setup.py bdist_wheel for urwid
  Stored in directory: /Users/philipjohnson/Library/Caches/pip/wheels/4d/93/ba/40b11569d0cdc1a4e807ed34a9672b0fbfa57aa36972b7c82a
Successfully built urwid
Installing collected packages: urwid
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 339, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip/wheel.py", line 310, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 71, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/urwid'
[~/Desktop]-> sudo pip install urwid
The directory '/Users/philipjohnson/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/philipjohnson/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting urwid
Installing collected packages: urwid
Successfully installed urwid-1.3.0
[~/Desktop]-> cd 
[~/Library/Caches/pip]-> sudo pip install PyYaml
The directory '/Users/philipjohnson/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/philipjohnson/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting PyYaml
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |████████████████████████████████| 249kB 996kB/s 
Installing collected packages: PyYaml
  Running setup.py install for PyYaml
Successfully installed PyYaml-3.11
[~/Library/Caches/pip]-> cd
[~]-> cd github/philipmjohnson/ics314f15/
[~/github/philipmjohnson/ics314f15]-> ls
README.md           morea-install.sh        morea-module-status.py      morea-run-local.sh
gh-pages            morea-lintui.py         morea-publish.sh        morea-vanilla-install.sh
master              morea-merge-upstream.sh     morea-pull.sh
[~/github/philipmjohnson/ics314f15]-> chmod 775 morea-lintui.py 
[~/github/philipmjohnson/ics314f15]-> ./morea-lintui.py 
Traceback (most recent call last):
  File "./morea-lintui.py", line 8, in <module>
    from MOREA.MoreaContent import MoreaContent
ImportError: No module named MOREA.MoreaContent
[~/github/philipmjohnson/ics314f15]-> 
```

**Comment by henricasanova** [comment]
the install process has been overhauled and is now smoother
